In [25]:
import pandas as pd;
import numpy as np;

Extraction:

In [60]:
df= pd.read_csv('pension_dataset_20000.csv')

In [62]:
df.head()

,pensioner_id,name,dob,gender,join_date,retirement_date,years_of_service,monthly_pension,pension_type,lump_sum,region,last_contribution,spouse_count,beneficiary_name,payment_method,bank_account_mask,inflation_index,active_flag,created_at
0,P000001,Michael Martin,1973-12-22,M,1997-04-16,2030-07-10,17,735.61,Defined Benefit,0.00,West,2029-08-14,1,James Lopez,Bank Transfer,XXXX-XXXX-7396,1.0151,1,2023-11-11T17:10:25.588933
1,P000002,Thomas Martinez,1936-11-29,F,1968-05-29,2005-09-29,25,1756.99,Defined Benefit,0.00,South,2004-03-16,0,NaN,Bank Transfer,XXXX-XXXX-8513,1.0197,0,2024-05-12T17:10:25.589190
2,P000003,Mary Martin,1944-11-18,M,1974-04-03,2005-12-07,16,1042.74,Defined Contribution,0.00,East,2005-05-16,0,NaN,Bank Transfer,XXXX-XXXX-5297,1.0159,0,2023-03-08T17:10:25.589500
3,P000004,Susan Thomas,1948-05-21,M,1974-05-09,2018-04-06,23,1844.33,Defined Benefit,0.00,North,2018-02-13,0,James Lopez,Bank Transfer,XXXX-XXXX-6258,1.0209,0,2021-09-27T17:10:25.589788
4,P000005,Thomas Davis,1964-11-20,F,1987-03-19,2024-12-15,42,2172.51,Defined Benefit,60830.28,East,2024-11-18,1,John Smith,Bank Transfer,XXXX-XXXX-9110,1.0298,0,2021-11-03T17:10:25.590267

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   pensioner_id       20000 non-null  object
 1   name               20000 non-null  object
 2   dob                20000 non-null  object
 3   gender             20000 non-null  object
 4   join_date          20000 non-null  object
 5   retirement_date    20000 non-null  object
 6   years_of_service   20000 non-null  int64
 7   monthly_pension    20000 non-null  float64
 8   pension_type       20000 non-null  object
 9   lump_sum           20000 non-null  float64
 10  region             20000 non-null  object
 11  last_contribution  20000 non-null  object
 12  spouse_count       20000 non-null  int64
 13  beneficiary_name   11986 non-null  object
 14  payment_method     20000 non-null  object
 15  bank_account_mask  20000 non-null  object
 16  inflation_index    20000 non-null  float64
 17  active_flag        20000 non-null  int64
 18  created_at         20000 non-null  object
dtypes: float64(3), int64(3), object(13)
memory usage: 2.9+ MB

Cleaning And Standardization:

In [82]:
df.isnull().sum()

pensioner_id         0
name                 0
dob                  0
gender               0
join_date            0
retirement_date      0
years_of_service     0
monthly_pension      0
pension_type         0
lump_sum             0
region               0
last_contribution    0
spouse_count         0
beneficiary_name     0
payment_method       0
bank_account_mask    0
inflation_index      0
active_flag          0
created_at           0
dtype: int64

In [84]:
df.dropna(subset=['beneficiary_name'], inplace=True)

In [86]:
df.isnull().sum()

pensioner_id         0
name                 0
dob                  0
gender               0
join_date            0
retirement_date      0
years_of_service     0
monthly_pension      0
pension_type         0
lump_sum             0
region               0
last_contribution    0
spouse_count         0
beneficiary_name     0
payment_method       0
bank_account_mask    0
inflation_index      0
active_flag          0
created_at           0
dtype: int64

In [88]:
df.duplicated().sum()

0

In [90]:
len(df)

11986

In [92]:
df.drop_duplicates()

,pensioner_id,name,dob,gender,join_date,retirement_date,years_of_service,monthly_pension,pension_type,lump_sum,region,last_contribution,spouse_count,beneficiary_name,payment_method,bank_account_mask,inflation_index,active_flag,created_at
0,P000001,Michael Martin,1973-12-22,M,1997-04-16,2030-07-10,17,735.61,Defined Benefit,0.00,West,2029-08-14,1,James Lopez,Bank Transfer,XXXX-XXXX-7396,1.0151,1,2023-11-11T17:10:25.588933
3,P000004,Susan Thomas,1948-05-21,M,1974-05-09,2018-04-06,23,1844.33,Defined Benefit,0.00,North,2018-02-13,0,James Lopez,Bank Transfer,XXXX-XXXX-6258,1.0209,0,2021-09-27T17:10:25.589788
4,P000005,Thomas Davis,1964-11-20,F,1987-03-19,2024-12-15,42,2172.51,Defined Benefit,60830.28,East,2024-11-18,1,John Smith,Bank Transfer,XXXX-XXXX-9110,1.0298,0,2021-11-03T17:10:25.590267
8,P000009,Robert Taylor,1975-11-27,M,1994-06-29,2035-06-24,11,1190.12,Defined Benefit,0.00,East,2034-06-05,1,Jennifer Jones,Bank Transfer,XXXX-XXXX-1197,1.0158,1,2023-03-22T17:10:25.591506
9,P000010,David Thomas,1967-09-24,F,1990-12-25,2035-06-28,18,1915.00,Defined Benefit,26810.00,South,2034-05-22,1,Sarah Martinez,Bank Transfer,XXXX-XXXX-7287,1.0261,1,2024-12-17T17:10:25.591832
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19992,P019993,Karen Williams,1938-03-17,M,1959-09-18,2006-12-27,37,1820.60,Defined Benefit,0.00,East,2005-09-30,0,Mary Lopez,Direct Deposit,XXXX-XXXX-3915,1.0219,0,2022-02-15T17:10:32.137127
19993,P019994,Barbara Jackson,1949-02-03,M,1966-08-14,2019-08-21,41,2669.43,Defined Benefit,0.00,West,2018-06-16,1,Richard Smith,Bank Transfer,XXXX-XXXX-7532,1.0111,0,2021-07-10T17:10:32.137480
19996,P019997,Joseph Gonzalez,1959-04-17,F,1978-09-22,2023-07-24,38,2175.03,Defined Contribution,0.00,North,2022-09-08,0,Karen Wilson,Cheque,XXXX-XXXX-2907,1.0291,0,2021-07-20T17:10:32.138335
19997,P019998,Charles Taylor,1965-07-09,F,1988-05-30,2031-05-22,29,1866.59,Defined Benefit,0.00,North,2030-01-07,0,Karen Smith,Cheque,XXXX-XXXX-2945,1.0239,1,2023-05-14T17:10:32.138596
19999,P020000,Joseph Brown,1936-07-15,M,1956-09-15,1992-06-28,16,2063.66,Defined Contribution,30954.90,West,1991-10-11,0,Patricia Davis,Bank Transfer,XXXX-XXXX-8059,0.9878,0,2021-12-20T17:10:32.139125

In [94]:
df.dtypes

pensioner_id          object
name                  object
dob                   object
gender                object
join_date             object
retirement_date       object
years_of_service       int64
monthly_pension      float64
pension_type          object
lump_sum             float64
region                object
last_contribution     object
spouse_count           int64
beneficiary_name      object
payment_method        object
bank_account_mask     object
inflation_index      float64
active_flag            int64
created_at            object
dtype: object

Data Consistency & Derivation:

Deriving new metrics such as age at retirement and pension status.

In [117]:
df['retirement_date']= pd.to_datetime(df['retirement_date'])

In [119]:
df['dob']=pd.to_datetime(df['dob'])

In [123]:
df[['retirement_date','dob']].info()

<class 'pandas.core.frame.DataFrame'>
Index: 11986 entries, 0 to 19999
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   retirement_date  11986 non-null  datetime64[ns]
 1   dob              11986 non-null  datetime64[ns]
dtypes: datetime64[ns](2)
memory usage: 280.9 KB

In [168]:
df['age']=((df['retirement_date']-df['dob']).dt.days/365.25).astype(int)

In [170]:
df

,pensioner_id,name,dob,gender,join_date,retirement_date,years_of_service,monthly_pension,pension_type,lump_sum,region,last_contribution,spouse_count,beneficiary_name,payment_method,bank_account_mask,inflation_index,active_flag,created_at,age
0,P000001,Michael Martin,1973-12-22,M,1997-04-16,2030-07-10,33,735.61,Defined Benefit,0.00,West,2029-08-14,1,James Lopez,Bank Transfer,XXXX-XXXX-7396,1.0151,1,2023-11-11T17:10:25.588933,56
3,P000004,Susan Thomas,1948-05-21,M,1974-05-09,2018-04-06,43,1844.33,Defined Benefit,0.00,North,2018-02-13,0,James Lopez,Bank Transfer,XXXX-XXXX-6258,1.0209,0,2021-09-27T17:10:25.589788,69
4,P000005,Thomas Davis,1964-11-20,F,1987-03-19,2024-12-15,37,2172.51,Defined Benefit,60830.28,East,2024-11-18,1,John Smith,Bank Transfer,XXXX-XXXX-9110,1.0298,0,2021-11-03T17:10:25.590267,60
8,P000009,Robert Taylor,1975-11-27,M,1994-06-29,2035-06-24,40,1190.12,Defined Benefit,0.00,East,2034-06-05,1,Jennifer Jones,Bank Transfer,XXXX-XXXX-1197,1.0158,1,2023-03-22T17:10:25.591506,59
9,P000010,David Thomas,1967-09-24,F,1990-12-25,2035-06-28,44,1915.00,Defined Benefit,26810.00,South,2034-05-22,1,Sarah Martinez,Bank Transfer,XXXX-XXXX-7287,1.0261,1,2024-12-17T17:10:25.591832,67
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19992,P019993,Karen Williams,1938-03-17,M,1959-09-18,2006-12-27,47,1820.60,Defined Benefit,0.00,East,2005-09-30,0,Mary Lopez,Direct Deposit,XXXX-XXXX-3915,1.0219,0,2022-02-15T17:10:32.137127,68
19993,P019994,Barbara Jackson,1949-02-03,M,1966-08-14,2019-08-21,53,2669.43,Defined Benefit,0.00,West,2018-06-16,1,Richard Smith,Bank Transfer,XXXX-XXXX-7532,1.0111,0,2021-07-10T17:10:32.137480,70
19996,P019997,Joseph Gonzalez,1959-04-17,F,1978-09-22,2023-07-24,44,2175.03,Defined Contribution,0.00,North,2022-09-08,0,Karen Wilson,Cheque,XXXX-XXXX-2907,1.0291,0,2021-07-20T17:10:32.138335,64
19997,P019998,Charles Taylor,1965-07-09,F,1988-05-30,2031-05-22,42,1866.59,Defined Benefit,0.00,North,2030-01-07,0,Karen Smith,Cheque,XXXX-XXXX-2945,1.0239,1,2023-05-14T17:10:32.138596,65
19999,P020000,Joseph Brown,1936-07-15,M,1956-09-15,1992-06-28,35,2063.66,Defined Contribution,30954.90,West,1991-10-11,0,Patricia Davis,Bank Transfer,XXXX-XXXX-8059,0.9878,0,2021-12-20T17:10:32.139125,55

In [233]:
df['pension_status']= df.apply(
    lambda df : 'Active' if df['active_flag'] == 1
    else 'Retired' if df['retirement_date'] < pd.Timestamp.today()
    else 'Inactive',
    axis= 1)

In [234]:
df

,pensioner_id,name,dob,gender,join_date,retirement_date,years_of_service,monthly_pension,pension_type,lump_sum,...,last_contribution,spouse_count,beneficiary_name,payment_method,bank_account_mask,inflation_index,active_flag,created_at,age,pension_status
0,P000001,Michael Martin,1973-12-22,M,1997-04-16,2030-07-10,33,735.61,Defined Benefit,0.00,...,2029-08-14,1,James Lopez,Bank Transfer,XXXX-XXXX-7396,1.0151,1,2023-11-11T17:10:25.588933,56,Active
3,P000004,Susan Thomas,1948-05-21,M,1974-05-09,2018-04-06,43,1844.33,Defined Benefit,0.00,...,2018-02-13,0,James Lopez,Bank Transfer,XXXX-XXXX-6258,1.0209,0,2021-09-27T17:10:25.589788,69,Retired
4,P000005,Thomas Davis,1964-11-20,F,1987-03-19,2024-12-15,37,2172.51,Defined Benefit,60830.28,...,2024-11-18,1,John Smith,Bank Transfer,XXXX-XXXX-9110,1.0298,0,2021-11-03T17:10:25.590267,60,Retired
8,P000009,Robert Taylor,1975-11-27,M,1994-06-29,2035-06-24,40,1190.12,Defined Benefit,0.00,...,2034-06-05,1,Jennifer Jones,Bank Transfer,XXXX-XXXX-1197,1.0158,1,2023-03-22T17:10:25.591506,59,Active
9,P000010,David Thomas,1967-09-24,F,1990-12-25,2035-06-28,44,1915.00,Defined Benefit,26810.00,...,2034-05-22,1,Sarah Martinez,Bank Transfer,XXXX-XXXX-7287,1.0261,1,2024-12-17T17:10:25.591832,67,Active
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19992,P019993,Karen Williams,1938-03-17,M,1959-09-18,2006-12-27,47,1820.60,Defined Benefit,0.00,...,2005-09-30,0,Mary Lopez,Direct Deposit,XXXX-XXXX-3915,1.0219,0,2022-02-15T17:10:32.137127,68,Retired
19993,P019994,Barbara Jackson,1949-02-03,M,1966-08-14,2019-08-21,53,2669.43,Defined Benefit,0.00,...,2018-06-16,1,Richard Smith,Bank Transfer,XXXX-XXXX-7532,1.0111,0,2021-07-10T17:10:32.137480,70,Retired
19996,P019997,Joseph Gonzalez,1959-04-17,F,1978-09-22,2023-07-24,44,2175.03,Defined Contribution,0.00,...,2022-09-08,0,Karen Wilson,Cheque,XXXX-XXXX-2907,1.0291,0,2021-07-20T17:10:32.138335,64,Retired
19997,P019998,Charles Taylor,1965-07-09,F,1988-05-30,2031-05-22,42,1866.59,Defined Benefit,0.00,...,2030-01-07,0,Karen Smith,Cheque,XXXX-XXXX-2945,1.0239,1,2023-05-14T17:10:32.138596,65,Active
19999,P020000,Joseph Brown,1936-07-15,M,1956-09-15,1992-06-28,35,2063.66,Defined Contribution,30954.90,...,1991-10-11,0,Patricia Davis,Bank Transfer,XXXX-XXXX-8059,0.9878,0,2021-12-20T17:10:32.139125,55,Retired

In [235]:
df[['retirement_date','pension_type','pension_status']]

      retirement_date          pension_type pension_status
0          2030-07-10       Defined Benefit         Active
3          2018-04-06       Defined Benefit        Retired
4          2024-12-15       Defined Benefit        Retired
8          2035-06-24       Defined Benefit         Active
9          2035-06-28       Defined Benefit         Active
...               ...                   ...            ...
19992      2006-12-27       Defined Benefit        Retired
19993      2019-08-21       Defined Benefit        Retired
19996      2023-07-24  Defined Contribution        Retired
19997      2031-05-22       Defined Benefit         Active
19999      1992-06-28  Defined Contribution        Retired

[11986 rows x 3 columns]

Crucial Update: Re-calculating the years_of_service field based on the logic (retirement_date - join_date) to resolve discrepancies between recorded 
service years and actual timeline data.

In [239]:
df['join_date']= pd.to_datetime(df['join_date'])

In [242]:
df['years_of_service']=((df['retirement_date']-df['join_date']).dt.days/365.25).astype(int)

In [244]:
df

,pensioner_id,name,dob,gender,join_date,retirement_date,years_of_service,monthly_pension,pension_type,lump_sum,...,last_contribution,spouse_count,beneficiary_name,payment_method,bank_account_mask,inflation_index,active_flag,created_at,age,pension_status
0,P000001,Michael Martin,1973-12-22,M,1997-04-16,2030-07-10,33,735.61,Defined Benefit,0.00,...,2029-08-14,1,James Lopez,Bank Transfer,XXXX-XXXX-7396,1.0151,1,2023-11-11T17:10:25.588933,56,Active
3,P000004,Susan Thomas,1948-05-21,M,1974-05-09,2018-04-06,43,1844.33,Defined Benefit,0.00,...,2018-02-13,0,James Lopez,Bank Transfer,XXXX-XXXX-6258,1.0209,0,2021-09-27T17:10:25.589788,69,Retired
4,P000005,Thomas Davis,1964-11-20,F,1987-03-19,2024-12-15,37,2172.51,Defined Benefit,60830.28,...,2024-11-18,1,John Smith,Bank Transfer,XXXX-XXXX-9110,1.0298,0,2021-11-03T17:10:25.590267,60,Retired
8,P000009,Robert Taylor,1975-11-27,M,1994-06-29,2035-06-24,40,1190.12,Defined Benefit,0.00,...,2034-06-05,1,Jennifer Jones,Bank Transfer,XXXX-XXXX-1197,1.0158,1,2023-03-22T17:10:25.591506,59,Active
9,P000010,David Thomas,1967-09-24,F,1990-12-25,2035-06-28,44,1915.00,Defined Benefit,26810.00,...,2034-05-22,1,Sarah Martinez,Bank Transfer,XXXX-XXXX-7287,1.0261,1,2024-12-17T17:10:25.591832,67,Active
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19992,P019993,Karen Williams,1938-03-17,M,1959-09-18,2006-12-27,47,1820.60,Defined Benefit,0.00,...,2005-09-30,0,Mary Lopez,Direct Deposit,XXXX-XXXX-3915,1.0219,0,2022-02-15T17:10:32.137127,68,Retired
19993,P019994,Barbara Jackson,1949-02-03,M,1966-08-14,2019-08-21,53,2669.43,Defined Benefit,0.00,...,2018-06-16,1,Richard Smith,Bank Transfer,XXXX-XXXX-7532,1.0111,0,2021-07-10T17:10:32.137480,70,Retired
19996,P019997,Joseph Gonzalez,1959-04-17,F,1978-09-22,2023-07-24,44,2175.03,Defined Contribution,0.00,...,2022-09-08,0,Karen Wilson,Cheque,XXXX-XXXX-2907,1.0291,0,2021-07-20T17:10:32.138335,64,Retired
19997,P019998,Charles Taylor,1965-07-09,F,1988-05-30,2031-05-22,42,1866.59,Defined Benefit,0.00,...,2030-01-07,0,Karen Smith,Cheque,XXXX-XXXX-2945,1.0239,1,2023-05-14T17:10:32.138596,65,Active
19999,P020000,Joseph Brown,1936-07-15,M,1956-09-15,1992-06-28,35,2063.66,Defined Contribution,30954.90,...,1991-10-11,0,Patricia Davis,Bank Transfer,XXXX-XXXX-8059,0.9878,0,2021-12-20T17:10:32.139125,55,Retired

Privacy Protection: Masking sensitive fields (e.g., beneficiary names, account
details).

In [255]:
df['name']= df['name'].apply(
    lambda x : '*' * (len(x)-3)+x[-3:] if pd.notna(x) else x )

In [257]:
df

,pensioner_id,name,dob,gender,join_date,retirement_date,years_of_service,monthly_pension,pension_type,lump_sum,...,last_contribution,spouse_count,beneficiary_name,payment_method,bank_account_mask,inflation_index,active_flag,created_at,age,pension_status
0,P000001,***********tin,1973-12-22,M,1997-04-16,2030-07-10,33,735.61,Defined Benefit,0.00,...,2029-08-14,1,James Lopez,Bank Transfer,XXXX-XXXX-7396,1.0151,1,2023-11-11T17:10:25.588933,56,Active
3,P000004,*********mas,1948-05-21,M,1974-05-09,2018-04-06,43,1844.33,Defined Benefit,0.00,...,2018-02-13,0,James Lopez,Bank Transfer,XXXX-XXXX-6258,1.0209,0,2021-09-27T17:10:25.589788,69,Retired
4,P000005,*********vis,1964-11-20,F,1987-03-19,2024-12-15,37,2172.51,Defined Benefit,60830.28,...,2024-11-18,1,John Smith,Bank Transfer,XXXX-XXXX-9110,1.0298,0,2021-11-03T17:10:25.590267,60,Retired
8,P000009,**********lor,1975-11-27,M,1994-06-29,2035-06-24,40,1190.12,Defined Benefit,0.00,...,2034-06-05,1,Jennifer Jones,Bank Transfer,XXXX-XXXX-1197,1.0158,1,2023-03-22T17:10:25.591506,59,Active
9,P000010,*********mas,1967-09-24,F,1990-12-25,2035-06-28,44,1915.00,Defined Benefit,26810.00,...,2034-05-22,1,Sarah Martinez,Bank Transfer,XXXX-XXXX-7287,1.0261,1,2024-12-17T17:10:25.591832,67,Active
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19992,P019993,***********ams,1938-03-17,M,1959-09-18,2006-12-27,47,1820.60,Defined Benefit,0.00,...,2005-09-30,0,Mary Lopez,Direct Deposit,XXXX-XXXX-3915,1.0219,0,2022-02-15T17:10:32.137127,68,Retired
19993,P019994,************son,1949-02-03,M,1966-08-14,2019-08-21,53,2669.43,Defined Benefit,0.00,...,2018-06-16,1,Richard Smith,Bank Transfer,XXXX-XXXX-7532,1.0111,0,2021-07-10T17:10:32.137480,70,Retired
19996,P019997,************lez,1959-04-17,F,1978-09-22,2023-07-24,44,2175.03,Defined Contribution,0.00,...,2022-09-08,0,Karen Wilson,Cheque,XXXX-XXXX-2907,1.0291,0,2021-07-20T17:10:32.138335,64,Retired
19997,P019998,***********lor,1965-07-09,F,1988-05-30,2031-05-22,42,1866.59,Defined Benefit,0.00,...,2030-01-07,0,Karen Smith,Cheque,XXXX-XXXX-2945,1.0239,1,2023-05-14T17:10:32.138596,65,Active
19999,P020000,*********own,1936-07-15,M,1956-09-15,1992-06-28,35,2063.66,Defined Contribution,30954.90,...,1991-10-11,0,Patricia Davis,Bank Transfer,XXXX-XXXX-8059,0.9878,0,2021-12-20T17:10:32.139125,55,Retired

In [270]:
df.to_csv('pension_dataset.csv', index=False)

Loading: Storing the cleaned and verified dataset into an SQLite database
(pensions.db).

In [272]:
from sqlalchemy import create_engine

In [274]:
username = "root2" 
password = "Mikey%409110311694" 
host = "localhost"
port = 3306 
database = "pension" 
engine = create_engine( f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}" )

In [276]:
try:
    with engine.connect() as conn:
        print("Connection successful — password is correct")
except Exception as e:
    print("Connection failed — password may be wrong or MySQL is not running")
    print("Error:", e)

Connection successful — password is correct

In [278]:
df.to_sql("pension", engine, if_exists="replace", index=False)

11986